/// Writes the generated sample content to a folder (used by
/// `tool/export_samples.dart` and tests). Pure Dart + `dart:io`.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart' show sha256;
import 'package:path/path.dart' as p;

import 'sample_content.dart';

/// Sub-folders owned (and replaced) by the exporter.
const List<String> sampleExportFolders = ['neon-dungeon', 'packages', 'profiles'];

class SampleExportResult {
  const SampleExportResult(this.outDir, this.files);

  final String outDir;

  /// Relative path (forward slashes) -> bytes of every file written, sorted.
  final Map<String, Uint8List> files;

  int get totalBytes => files.values.fold(0, (sum, b) => sum + b.length);
}

/// Exports [bundle] (default: freshly generated) into [outDir]:
/// `neon-dungeon/**`, `packages/*.j3mod`, `profiles/*.j3profile.json`,
/// `README.md`, `SHA256SUMS.txt` plus `.gitignore`/`.gitattributes` that
/// keep the files byte-exact in git. Only the folders in
/// [sampleExportFolders] are deleted before writing; nothing else in
/// [outDir] is touched.
Future<SampleExportResult> exportSamples(String outDir, {SampleBundle? bundle}) async {
  final b = bundle ?? buildSampleBundle();
  final root = p.normalize(p.absolute(outDir));
  await Directory(root).create(recursive: true);
  for (final sub in sampleExportFolders) {
    final dir = Directory(p.join(root, sub));
    if (await dir.exists()) await dir.delete(recursive: true);
  }

  final content = <String, Uint8List>{
    for (final e in b.files.entries) 'neon-dungeon/${e.key}': e.value,
    for (final e in b.packages.entries) 'packages/${e.key}': e.value,
    for (final e in b.profiles.entries) 'profiles/${e.key}': e.value,
  };
  content['README.md'] = Uint8List.fromList(utf8.encode(_readme(b, content)));
  final sorted = content.keys.toList()..sort();
  final sums = StringBuffer();
  for (final rel in sorted) {
    sums.writeln('${sha256.convert(content[rel]!)}  $rel');
  }
  final all = <String, Uint8List>{
    for (final rel in sorted) rel: content[rel]!,
    'SHA256SUMS.txt': Uint8List.fromList(utf8.encode(sums.toString())),
    // The repository ignores *.log; the sample logs are real content.
    '.gitignore': Uint8List.fromList(utf8.encode('# Generated by tool/export_samples.dart\n!*.log\n')),
    // No end-of-line conversion: SHA256SUMS.txt must match on every OS.
    '.gitattributes': Uint8List.fromList(utf8.encode('# Generated by tool/export_samples.dart\n* -text\n')),
  };
  for (final e in all.entries) {
    final file = File(p.joinAll([root, ...e.key.split('/')]));
    await file.parent.create(recursive: true);
    await file.writeAsBytes(e.value, flush: true);
  }
  return SampleExportResult(root, all);
}

String _readme(SampleBundle b, Map<String, Uint8List> content) {
  final out = StringBuffer()
    ..writeln('# Samples (generated)')
    ..writeln()
    ..writeln('Everything in this folder is generated by `dart run tool/export_samples.dart` from')
    ..writeln('`lib/features/sample/sample_content.dart`. Do not edit these files by hand: change the')
    ..writeln('generator and run the tool again. The output is byte-for-byte deterministic and')
    ..writeln('`SHA256SUMS.txt` lists every file (`cd samples && sha256sum -c SHA256SUMS.txt`).')
    ..writeln()
    ..writeln('"$sampleGameName" is a fictional game invented for these samples. All content is CC0-1.0.')
    ..writeln('The app creates the same content as its disposable sample workspace on first run')
    ..writeln('(see `docs/SAMPLES.md`); package and profile formats are in `docs/MOD_FORMAT.md`.')
    ..writeln()
    ..writeln('| Path | Content |')
    ..writeln('| --- | --- |')
    ..writeln('| `neon-dungeon/` | the sample workspace exactly as the app writes it (${b.files.length} files) |')
    ..writeln('| `packages/` | the ${b.packages.length} `.j3mod` packages of the workspace mod library |')
    ..writeln('| `profiles/` | the ${b.profiles.length} `.j3profile.json` profiles (all target `game`) |')
    ..writeln('| `SHA256SUMS.txt` | SHA-256 of every file above and this README |')
    ..writeln()
    ..writeln('## Packages')
    ..writeln()
    ..writeln('| Package | Depends on | Writes (relative to `game/`) |')
    ..writeln('| --- | --- | --- |');
  for (final pkg in samplePackageList()) {
    final deps = pkg.dependencies.isEmpty
        ? '-'
        : pkg.dependencies.map((d) => '`${d['id']}` ${d['version'] ?? 'any'}').join(', ');
    out.writeln('| `${pkg.fileName}` | $deps | ${pkg.payload.keys.map((t) => '`$t`').join(', ')} |');
  }
  out
    ..writeln()
    ..writeln('## Profiles')
    ..writeln()
    ..writeln('| Profile | Mods (application order) | Demonstrates |')
    ..writeln('| --- | --- | --- |');
  for (final prof in sampleProfileList) {
    out.writeln('| `${prof.id}` "${prof.name}" | ${prof.mods.join(', ')} | ${prof.description} |');
  }
  out
    ..writeln()
    ..writeln('## Files')
    ..writeln()
    ..writeln('| File | Bytes |')
    ..writeln('| --- | ---: |');
  final keys = content.keys.where((k) => k != 'README.md').toList()..sort();
  for (final k in keys) {
    out.writeln('| `$k` | ${content[k]!.length} |');
  }
  return out.toString();
}
