import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Asset (relative to `assets/`) of the synthesized intro sting. Generated by
/// `tool/sound/generate_intro_sound.py`; see docs/INTRO.md.
const String kIntroSoundAsset = 'sounds/intro_laugh.wav';

/// Plays the intro sting. Implementations never throw and never block the
/// intro: every failure is caught and logged with [debugPrint].
abstract class IntroSound {
  /// Starts playback at [volume] (0..1). [position] returns where in the clip
  /// playback should be *now*; it is read again once the clip is prepared so
  /// preparation latency does not push the "HA"s off the jaw.
  Future<void> start({required double volume, required Duration Function() position});

  /// Stops immediately (mute or skip).
  void stop();

  /// Releases the player.
  void dispose();
}

/// Factory for the intro sound. Tests override it with a fake so no audio
/// plugin is ever touched.
final introSoundProvider = Provider<IntroSound Function()>((ref) => AudioplayersIntroSound.new);

/// [IntroSound] backed by `audioplayers`. The [AudioPlayer] is created lazily
/// in [start], i.e. only when sound is enabled.
class AudioplayersIntroSound implements IntroSound {
  AudioPlayer? _player;
  bool _stopped = false;
  bool _disposed = false;

  /// Below this the clip is simply started from the beginning.
  static const Duration _syncTolerance = Duration(milliseconds: 40);

  @override
  Future<void> start({required double volume, required Duration Function() position}) async {
    if (_stopped || _disposed || _player != null) return;
    try {
      final player = _player = AudioPlayer();
      await player.setReleaseMode(ReleaseMode.stop);
      await player.setVolume(volume.clamp(0.0, 1.0));
      await player.setSource(AssetSource(kIntroSoundAsset));
      if (_stopped || _disposed) return;
      final at = position();
      if (at > _syncTolerance) await player.seek(at);
      if (_stopped || _disposed) return;
      await player.resume();
      // A mute/skip may have landed while resume() was in flight.
      if (_stopped || _disposed) await player.stop();
    } catch (e) {
      debugPrint('Intro sound unavailable: $e');
    }
  }

  @override
  void stop() {
    if (_stopped) return;
    _stopped = true;
    final player = _player;
    if (player == null) return;
    unawaited(
      player.stop().catchError((Object e) {
        debugPrint('Intro sound stop failed: $e');
      }),
    );
  }

  @override
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _stopped = true;
    final player = _player;
    _player = null;
    if (player == null) return;
    unawaited(
      player.dispose().catchError((Object e) {
        debugPrint('Intro sound dispose failed: $e');
      }),
    );
  }
}
