import 'dart:convert';
import 'dart:typed_data';

import 'package:archive/archive.dart' show Archive, ArchiveFile, CompressionType, ZipEncoder;

import 'sample_art.dart';
import 'sample_texts.dart';

/// Fixed timestamp stored in every sample archive entry.
final DateTime sampleArchiveTime = DateTime(2026, 9, 1, 12);

const Map<String, String> _gameCompat = {'game': sampleGameId, 'gameVersion': '>=1.4.0 <2.0.0'};

/// One sample mod package (see docs/MOD_FORMAT.md).
class SamplePackage {
  SamplePackage({
    required this.id,
    required this.name,
    required this.version,
    required this.description,
    required this.payload,
    required this.readmeNotes,
    this.compatibility = _gameCompat,
    this.dependencies = const [],
    this.conflicts = const [],
    this.tags = const [],
    this.preview,
  });

  final String id;
  final String name;
  final String version;
  final String description;

  /// Target path (relative to the profile target folder) -> content.
  final Map<String, List<int>> payload;
  final String readmeNotes;
  final Map<String, String> compatibility;
  final List<Map<String, String>> dependencies;
  final List<Map<String, String>> conflicts;
  final List<String> tags;
  final Uint8List? preview;

  String get fileName => '$id-$version.j3mod';

  Map<String, Object?> manifest() => {
    'format': 'j3mod',
    'formatVersion': 1,
    'id': id,
    'name': name,
    'version': version,
    'description': description,
    'author': 'J3NSONTOP samples',
    'license': 'CC0-1.0',
    'compatibility': compatibility,
    'files': [
      for (final target in payload.keys) {'source': 'files/$target', 'target': target},
    ],
    if (dependencies.isNotEmpty) 'dependencies': dependencies,
    if (conflicts.isNotEmpty) 'conflicts': conflicts,
    if (tags.isNotEmpty) 'tags': tags,
  };

  String readme() {
    final b = StringBuffer()
      ..writeln('# $name $version')
      ..writeln()
      ..writeln(description)
      ..writeln()
      ..writeln(
        'Sample package for the fictional game *$sampleGameName* '
        '(`${compatibility['game']}` ${compatibility['gameVersion'] ?? 'any version'}), '
        'generated by J3NSONTOP. License: CC0-1.0.',
      )
      ..writeln()
      ..writeln('## Files')
      ..writeln()
      ..writeln('| Package source | Target (inside the profile target folder) |')
      ..writeln('| --- | --- |');
    for (final target in payload.keys) {
      b.writeln('| `files/$target` | `$target` |');
    }
    b
      ..writeln()
      ..writeln('## Dependencies')
      ..writeln();
    if (dependencies.isEmpty) {
      b.writeln('None.');
    } else {
      for (final d in dependencies) {
        b.writeln('- `${d['id']}` ${d['version'] ?? 'any'}');
      }
    }
    b
      ..writeln()
      ..writeln('## Notes')
      ..writeln()
      ..writeln(readmeNotes);
    return b.toString();
  }

  /// Deterministic ZIP bytes: Stored entries, fixed timestamps, fixed order.
  /// Stored (not Deflate) keeps the bytes identical on every platform, since
  /// the platform zlib may compress differently.
  Uint8List zip() {
    final archive = Archive();
    void add(String name, List<int> bytes) {
      archive.add(ArchiveFile.bytes(name, bytes)..compression = CompressionType.none);
    }

    add('j3mod.json', utf8.encode(prettyJsonText(manifest())));
    add('README.md', utf8.encode(readme()));
    if (preview != null) add('preview.png', preview!);
    payload.forEach((target, bytes) => add('files/$target', bytes));
    return ZipEncoder().encodeBytes(archive, modified: sampleArchiveTime);
  }
}

/// The seven sample packages, in documentation order.
List<SamplePackage> samplePackageList() => [
  SamplePackage(
    id: 'core-patch',
    name: 'Core Patch',
    version: '1.0.0',
    description:
        'Community fixes for Neon Dungeon 1.4.2: corrects UI typos in the English strings and adds '
        'data/core_patch.json, which other packages build on.',
    payload: {
      'data/core_patch.json': utf8.encode(corePatchJson()),
      'data/localization/en.json': utf8.encode(enJson(patched: true)),
    },
    tags: const ['fix', 'localization'],
    readmeNotes:
        'Creates `data/core_patch.json` (new file) and overwrites `data/localization/en.json` '
        '("Qiut" -> "Quit", "recieve" -> "receive"). `hardcore-balance` depends on it.',
  ),
  SamplePackage(
    id: 'neon-hud',
    name: 'Neon HUD',
    version: '1.2.0',
    description: 'Recolours the HUD in neon red with a soft glow.',
    payload: {'data/ui/hud.json': utf8.encode(hudJson(neon: true))},
    conflicts: const [
      {'id': 'classic-hud', 'reason': 'Both replace the HUD layout.'},
    ],
    tags: const ['ui', 'cosmetic'],
    preview: neonHudPreview(),
    readmeNotes:
        'Has no dependencies: the simplest apply / rollback demo (profile "Vanilla+ HUD"). '
        'Declares a conflict with `classic-hud`, a package that is not in the sample library.',
  ),
  SamplePackage(
    id: 'hardcore-balance',
    name: 'Hardcore Balance',
    version: '2.0.1',
    description: 'Fewer resources, tougher enemies, pricier shops. Built on top of core-patch.',
    payload: {
      'config/balance.toml': utf8.encode(balanceToml(BalancePreset.hardcore)),
      'data/items.csv': utf8.encode(itemsCsv(hardcore: true)),
    },
    dependencies: const [
      {'id': 'core-patch', 'version': '^1.0.0'},
    ],
    tags: const ['balance', 'difficulty'],
    readmeNotes:
        'Requires `core-patch` ^1.0.0 earlier in the profile order. Replaces `config/balance.toml`, '
        'which `brutal-mode` also replaces (see profile "Conflict demo").',
  ),
  SamplePackage(
    id: 'brutal-mode',
    name: 'Brutal Mode',
    version: '0.9.0',
    description: 'Pre-release: one life, glass-cannon enemies. Replaces config/balance.toml.',
    payload: {'config/balance.toml': utf8.encode(balanceToml(BalancePreset.brutal))},
    tags: const ['balance', 'difficulty', 'experimental'],
    readmeNotes:
        'Intentionally overlaps `hardcore-balance`: both write `config/balance.toml`. Overlaps are '
        'allowed but always reported; the package applied last wins.',
  ),
  SamplePackage(
    id: 'legacy-skin',
    name: 'Legacy Skin',
    version: '0.3.0',
    description: 'Four-shade handheld-green hero sprite from the retro era.',
    payload: {'sprites/hero_walk.png': heroWalkSheet(HeroPalette.retro)},
    compatibility: const {'game': sampleGameId, 'gameVersion': '>=1.2.0 <2.0.0'},
    dependencies: const [
      {'id': 'retro-core', 'version': '^1.0.0'},
    ],
    tags: const ['skin', 'retro'],
    readmeNotes:
        'Depends on `retro-core`, which does not exist anywhere: the missing-dependency demo '
        '(profile "Broken dependencies").',
  ),
  SamplePackage(
    id: 'cycle-a',
    name: 'Cycle A',
    version: '1.0.0',
    description: 'Dependency cycle demo, part A (depends on cycle-b).',
    payload: {'data/cycle_a.json': utf8.encode(cycleJson('cycle-a', 'cycle-b'))},
    compatibility: const {'game': sampleGameId},
    dependencies: const [
      {'id': 'cycle-b', 'version': '^1.0.0'},
    ],
    tags: const ['demo'],
    readmeNotes: '`cycle-a` -> `cycle-b` -> `cycle-a`: no valid order exists, so the cycle is reported.',
  ),
  SamplePackage(
    id: 'cycle-b',
    name: 'Cycle B',
    version: '1.0.0',
    description: 'Dependency cycle demo, part B (depends on cycle-a).',
    payload: {'data/cycle_b.json': utf8.encode(cycleJson('cycle-b', 'cycle-a'))},
    compatibility: const {'game': sampleGameId},
    dependencies: const [
      {'id': 'cycle-a', 'version': '^1.0.0'},
    ],
    tags: const ['demo'],
    readmeNotes: '`cycle-b` -> `cycle-a` -> `cycle-b`: no valid order exists, so the cycle is reported.',
  ),
];

/// One sample profile (see docs/MOD_FORMAT.md).
class SampleProfile {
  const SampleProfile(this.id, this.name, this.description, this.mods);
  final String id;
  final String name;
  final String description;
  final List<String> mods;

  String get fileName => '$id.j3profile.json';

  Map<String, Object?> toJson() => {
    'format': 'j3profile',
    'formatVersion': 1,
    'id': id,
    'name': name,
    'description': description,
    'target': 'game',
    'mods': [
      for (final m in mods) {'id': m, 'enabled': true},
    ],
  };
}

/// The four sample profiles, in documentation order.
const List<SampleProfile> sampleProfileList = [
  SampleProfile('vanilla-plus', 'Vanilla+ HUD', 'Just the neon HUD: the simplest apply and rollback.', ['neon-hud']),
  SampleProfile('hardcore-run', 'Hardcore run', 'Core patch + hardcore balance + neon HUD (dependencies in order).', [
    'core-patch',
    'hardcore-balance',
    'neon-hud',
  ]),
  SampleProfile(
    'conflict-demo',
    'Conflict demo',
    'hardcore-balance and brutal-mode both replace config/balance.toml; brutal-mode (last) wins.',
    ['core-patch', 'hardcore-balance', 'brutal-mode'],
  ),
  SampleProfile(
    'broken-deps',
    'Broken dependencies',
    'legacy-skin needs the missing retro-core; cycle-a and cycle-b depend on each other.',
    ['legacy-skin', 'cycle-a', 'cycle-b'],
  ),
];
