import 'dart:convert';

// Text content of the Neon Dungeon sample workspace. "Neon Dungeon" is a
// fictional game; every value here is invented for demonstration.

const String sampleGameId = 'neon-dungeon';
const String sampleGameName = 'Neon Dungeon';
const String sampleGameVersion = '1.4.2';
const String sampleGameBuild = '2026.09.01-r1842';

const JsonEncoder _json = JsonEncoder.withIndent('  ');

/// Pretty JSON with a trailing newline.
String prettyJsonText(Object? value) => '${_json.convert(value)}\n';

const String readmeTxt = r'''
        .-""""-.
       /  _  _  \        J3NSONTOP BIGGEST MULTITOOL MADE
      |  (o)(o)  |       SAMPLE WORKSPACE :: NEON DUNGEON
      |    /\    |
       \ '====' /        ha. HA. HAHAHA.
        '-.__.-'

NEON DUNGEON (sample)
=====================

This workspace was generated by J3NSONTOP on first run so every tool has real
files to work on right away. "Neon Dungeon" is a fictional game invented for
these samples; nothing here belongs to a real game.

Everything is disposable: edit it, break it, apply mods to it. Resetting the
sample workspace (Workspaces section) regenerates the original files, and
removing it deletes only this app-owned copy.

WHAT'S INSIDE
-------------
  game/          the "installed game" that mod profiles are applied to
    game.json      identifies the target: neon-dungeon 1.4.2
    config/        settings.ini, graphics.json, controls.yaml, balance.toml
    data/          items.csv, enemies.tsv, HUD layout, English UI strings
    saves/         slot1.json + save.schema.json for the save-data editor
    sprites/       hero_walk.png (4x2 frames of 32x32) and six item icons
    textures/      logo.png (256x128 with transparency)
    logs/          game.log (~300 lines) and a crash report
  downloads/     the 7 sample mod packages (.j3mod); already imported into
                 this workspace's mod library together with 4 profiles
  duplicates/    exact copies (and one near-copy) for the duplicate finder
  rename-demo/   badly named files for the batch renamer
  notes/         a to-do list and a file with a Unicode name

THINGS TO TRY
-------------
  MODS
   1. Apply profile "Vanilla+ HUD" to game/. Check the plan (1 overwrite),
      open data/ui/hud.json, then roll back and compare again.
   2. "Hardcore run": core-patch -> hardcore-balance -> neon-hud. The
      dependency hardcore-balance -> core-patch ^1.0.0 is satisfied because
      core-patch comes first. Try moving it below and use "sort by
      dependencies".
   3. "Conflict demo": hardcore-balance and brutal-mode both replace
      config/balance.toml. That overlap is allowed but always shown; the
      last package in the order (brutal-mode) wins.
   4. "Broken dependencies": legacy-skin needs "retro-core", which does not
      exist, and cycle-a / cycle-b depend on each other. Applying is blocked
      and every problem is explained.
   5. Import a package from downloads/ again: the library keeps one version
      per id.

  CONFIG & DATA
   6. Validate and format game/config/*: INI sections and comments, nested
      JSON, YAML with an anchor + alias (convert it to JSON and see the alias
      expanded), TOML with an array of tables and a date-time.
   7. Edit game/saves/slot1.json with the save editor. Try gold = 1000000
      (maximum is 999999) or class = "bard" (not in the enum).
   8. Open game/data/items.csv: quoted fields with commas and escaped quotes,
      CRLF line endings. game/data/enemies.tsv has an empty cell.

  ASSETS
   9. Slice game/sprites/hero_walk.png into 8 frames and preview the walk
      cycle. Inspect alpha in the icons and textures/logo.png.

  FILES & DEV
  10. Filter game/logs/game.log by level (TRACE, DEBUG, INFO, WARN, ERROR,
      FATAL) and follow the crash into logs/crash-2026-09-01.log.
  11. Find duplicates in duplicates/ (one file only looks identical), hash
      files, batch-rename rename-demo/.

Generated deterministically by J3NSONTOP (sample content v1, 2026-09-01).
''';

String gameJson() => prettyJsonText({
  'id': sampleGameId,
  'name': sampleGameName,
  'version': sampleGameVersion,
  'build': sampleGameBuild,
  'releaseDate': '2026-09-01',
  'engine': 'NeonGL 4.6 (fictional)',
  'modding': {'packageFormat': 'j3mod', 'dataRoot': 'data'},
  'fictional': true,
});

const String settingsIni = '''
; Neon Dungeon - user settings
; Written by the launcher on 2026-09-01. Edit only while the game is closed.
; Lines starting with ; or # are comments.
config_version = 3
profile = default

[Display]
; Window mode: windowed | borderless | fullscreen
mode = borderless
width = 1920
height = 1080
refresh_rate = 144
vsync = true
ui_scale = 1.25
# Brightness in percent (50-150)
brightness = 100
language = en

[Audio]
master_volume = 0.8
music_volume = 0.6
sfx_volume = 0.9
voice_volume = 1.0
mute_when_unfocused = yes
output_device = "Default"

[Gameplay]
difficulty = normal
; Show damage numbers above enemies
damage_numbers = on
auto_pickup = true
camera_shake = 0.5
permadeath = false
tutorial_hints = true
save_slot = 1
# Leave empty for a random dungeon seed
seed =

[Network]
; LAN co-op only - this fictional game never talks to the internet
lan_coop = false
port = 27015
player_name = J3NSONTOP
''';

String graphicsJson() => prettyJsonText({
  'version': 2,
  'resolution': {'width': 1920, 'height': 1080, 'renderScale': 1.0},
  'display': {'mode': 'borderless', 'vsync': true, 'fpsLimit': 144, 'fov': 90.0, 'monitor': 0},
  'quality': {
    'preset': 'high',
    'textures': 'high',
    'shadows': 'medium',
    'particles': 0.75,
    'anisotropy': 8,
    'antialiasing': 'fxaa',
  },
  'postfx': {
    'bloom': {'enabled': true, 'intensity': 0.65, 'threshold': 0.8},
    'scanlines': {'enabled': true, 'opacity': 0.12, 'lineWidth': 2},
    'chromaticAberration': {'enabled': false, 'strength': 0.0},
    'vignette': {'enabled': true, 'radius': 0.75, 'color': '#1A0008'},
  },
  'palette': ['#0A0A0A', '#1A0008', '#FF1744', '#FF6E86', '#FFFFFF'],
  'presets': [
    {'name': 'low', 'shadows': 'off', 'bloom': false, 'particles': 0.25},
    {'name': 'medium', 'shadows': 'low', 'bloom': true, 'particles': 0.5},
    {'name': 'high', 'shadows': 'medium', 'bloom': true, 'particles': 0.75},
    {'name': 'ultra', 'shadows': 'high', 'bloom': true, 'particles': 1.0},
  ],
  'customShader': null,
  'gpuOverride': null,
  'debug': {'showFps': false, 'wireframe': false, 'logShaderCompiles': true},
});

const String controlsYaml = '''
# Neon Dungeon - controls
# Key names follow SDL ("Left Shift"); gamepad buttons use Xbox names.
# A list means "any of these keys". Edit only while the game is closed.
version: 2
layout: qwerty

# Shared look settings. Defined once with an anchor (&look) and reused
# below with aliases (*look) - YAML-to-JSON conversion expands both copies.
look_defaults: &look
  sensitivity: 1.25
  invert_y: false
  deadzone: 0.15 # stick deadzone, 0..1

keyboard:
  movement:
    up: [W, Up]
    down: [S, Down]
    left: [A, Left]
    right: [D, Right]
  actions:
    attack: Mouse1
    block: Mouse2
    dodge: Space
    sprint: "Left Shift"
    interact: E
    use_potion: Q
    inventory: Tab
    map: M
    pause: Escape
  hotbar:
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
  look: *look

gamepad:
  enabled: true
  vibration: 0.8
  movement: LeftStick
  camera: RightStick
  actions:
    attack: X
    block: LB
    dodge: A
    sprint: LS
    interact: Y
    use_potion: RB
    inventory: Back
    map: DPadUp
    pause: Start
  look: *look

macros:
  quick_heal:
    description: |
      Drinks the weakest healing potion in the inventory,
      then switches back to the equipped weapon.
    steps: [use_potion, wait_200ms, equip_last]
  panic_button: ~ # unbound
''';

/// A balance preset for `config/balance.toml`.
class BalancePreset {
  const BalancePreset({
    required this.title,
    required this.comment,
    required this.scale,
    required this.maxHealth,
    required this.maxMana,
    required this.critChance,
    required this.healthRegen,
    required this.startingGold,
    required this.sellRatio,
    required this.priceMultiplier,
    required this.drops,
    required this.enemyHealth,
    required this.enemyDamage,
    this.permadeath = false,
    this.startingItems = const ['rusty-sword', 'small-potion', 'small-potion'],
  });

  final String title;
  final String comment;
  final String scale;
  final int maxHealth;
  final int maxMana;
  final String critChance;
  final String healthRegen;
  final int startingGold;
  final String sellRatio;
  final String priceMultiplier;

  /// common, uncommon, rare, legendary
  final List<String> drops;

  /// Percent of vanilla enemy health / damage.
  final int enemyHealth;
  final int enemyDamage;
  final bool permadeath;
  final List<String> startingItems;

  static const vanilla = BalancePreset(
    title: 'Vanilla',
    comment: 'Vanilla 1.4.2 values. Mods may replace this file (see hardcore-balance, brutal-mode).',
    scale: '1.0',
    maxHealth: 100,
    maxMana: 50,
    critChance: '0.05',
    healthRegen: '0.5',
    startingGold: 150,
    sellRatio: '0.5',
    priceMultiplier: '1.0',
    drops: ['0.70', '0.20', '0.08', '0.02'],
    enemyHealth: 100,
    enemyDamage: 100,
  );

  static const hardcore = BalancePreset(
    title: 'Hardcore',
    comment: 'hardcore-balance 2.0.1: fewer resources, tougher enemies. Requires core-patch.',
    scale: '1.5',
    maxHealth: 70,
    maxMana: 40,
    critChance: '0.04',
    healthRegen: '0.2',
    startingGold: 50,
    sellRatio: '0.35',
    priceMultiplier: '1.5',
    drops: ['0.78', '0.16', '0.05', '0.01'],
    enemyHealth: 150,
    enemyDamage: 130,
    startingItems: ['rusty-sword', 'small-potion'],
  );

  static const brutal = BalancePreset(
    title: 'BRUTAL',
    comment: 'brutal-mode 0.9.0 (pre-release): one life, glass-cannon enemies. Overlaps hardcore-balance on purpose.',
    scale: '2.5',
    maxHealth: 40,
    maxMana: 25,
    critChance: '0.10',
    healthRegen: '0.0',
    startingGold: 0,
    sellRatio: '0.25',
    priceMultiplier: '2.0',
    drops: ['0.85', '0.12', '0.025', '0.005'],
    enemyHealth: 200,
    enemyDamage: 250,
    permadeath: true,
    startingItems: ['bone-club'],
  );
}

class _EnemyBase {
  const _EnemyBase(this.id, this.health, this.damage, this.xp, this.weight, {this.boss = false});
  final String id;
  final int health;
  final int damage;
  final int xp;
  final int weight;
  final bool boss;
}

const List<_EnemyBase> _balanceEnemies = [
  _EnemyBase('slime', 30, 4, 5, 40),
  _EnemyBase('skeleton', 45, 7, 12, 30),
  _EnemyBase('ghoul', 70, 10, 22, 18),
  _EnemyBase('neon-golem', 240, 22, 110, 6),
  _EnemyBase('lich', 900, 35, 1000, 1, boss: true),
];

String balanceToml(BalancePreset p) {
  final b = StringBuffer()
    ..writeln('# Neon Dungeon - balance values')
    ..writeln('# ${p.comment}')
    ..writeln()
    ..writeln('title = "${p.title}"')
    ..writeln('game_version = "$sampleGameVersion"')
    ..writeln('last_tuned = 2026-09-01T12:00:00Z')
    ..writeln('season_start = 2026-09-01')
    ..writeln('difficulty_scale = ${p.scale}')
    ..writeln('permadeath = ${p.permadeath}')
    ..writeln()
    ..writeln('[player]')
    ..writeln('max_health = ${p.maxHealth}')
    ..writeln('max_mana = ${p.maxMana}')
    ..writeln('move_speed = 4.5')
    ..writeln('crit_chance = ${p.critChance}')
    ..writeln('crit_multiplier = 1.5')
    ..writeln('starting_items = [${p.startingItems.map((s) => '"$s"').join(', ')}]')
    ..writeln('regen = { health_per_second = ${p.healthRegen}, mana_per_second = 1.0 }')
    ..writeln()
    ..writeln('[economy]')
    ..writeln('starting_gold = ${p.startingGold}')
    ..writeln('max_gold = 999_999')
    ..writeln('sell_ratio = ${p.sellRatio}')
    ..writeln('shop_restock_minutes = 10')
    ..writeln('price_multiplier = ${p.priceMultiplier}')
    ..writeln()
    ..writeln('[economy.drop_rates]')
    ..writeln('common = ${p.drops[0]}')
    ..writeln('uncommon = ${p.drops[1]}')
    ..writeln('rare = ${p.drops[2]}')
    ..writeln('legendary = ${p.drops[3]}');
  for (final e in _balanceEnemies) {
    b
      ..writeln()
      ..writeln('[[enemies]]')
      ..writeln('id = "${e.id}"')
      ..writeln('health = ${e.health * p.enemyHealth ~/ 100}')
      ..writeln('damage = ${e.damage * p.enemyDamage ~/ 100}')
      ..writeln('xp = ${e.xp}')
      ..writeln('spawn_weight = ${e.weight}');
    if (e.boss) b.writeln('boss = true');
  }
  return b.toString();
}

class _Item {
  const _Item(this.id, this.name, this.type, this.damage, this.price, this.rarity);
  final String id;
  final String name;
  final String type;
  final int damage;
  final int price;
  final String rarity;
}

const List<_Item> _items = [
  _Item('rusty-sword', 'Rusty Sword', 'weapon', 6, 15, 'common'),
  _Item('iron-sword', 'Iron Sword', 'weapon', 10, 60, 'common'),
  _Item('neon-blade', 'Neon Blade', 'weapon', 18, 420, 'rare'),
  _Item('bone-club', 'Bone Club', 'weapon', 8, 25, 'common'),
  _Item('short-bow', 'Bow, Short', 'weapon', 7, 45, 'common'),
  _Item('long-bow', 'Bow, Long', 'weapon', 11, 110, 'uncommon'),
  _Item('wooden-shield', 'Wooden Shield', 'shield', 0, 20, 'common'),
  _Item('tower-shield', 'Shield, Tower', 'shield', 0, 180, 'uncommon'),
  _Item('small-potion', 'Small Potion', 'consumable', 0, 10, 'common'),
  _Item('large-potion', 'Large Potion', 'consumable', 0, 35, 'uncommon'),
  _Item('mana-potion', 'Mana Potion', 'consumable', 0, 30, 'common'),
  _Item('elixir', 'Elixir of the Deep', 'consumable', 0, 250, 'rare'),
  _Item('bomb', 'Bomb', 'consumable', 40, 50, 'uncommon'),
  _Item('torch', 'Torch', 'tool', 2, 5, 'common'),
  _Item('dungeon-key', 'Dungeon Key', 'key', 0, 0, 'common'),
  _Item('skull-key', 'Skull Key', 'key', 0, 0, 'rare'),
  _Item('red-gem', 'Red Gem', 'gem', 0, 500, 'rare'),
  _Item('void-gem', 'Void Gem', 'gem', 0, 1200, 'legendary'),
  _Item('lucky-coin', 'Lucky Coin', 'trinket', 0, 77, 'uncommon'),
  _Item('laughing-skull', 'The "Laughing" Skull', 'trinket', 0, 666, 'legendary'),
];

/// Item ids in `data/items.csv` (used by the save file and tests).
List<String> get sampleItemIds => [for (final i in _items) i.id];

String _csvField(String v) =>
    v.contains(',') || v.contains('"') || v.contains('\n') ? '"${v.replaceAll('"', '""')}"' : v;

/// `data/items.csv` (RFC 4180, CRLF line endings). [hardcore] gives the
/// hardcore-balance variant: weaker weapons, higher prices.
String itemsCsv({bool hardcore = false}) {
  final rows = <List<String>>[
    ['id', 'name', 'type', 'damage', 'price', 'rarity'],
    for (final i in _items)
      [
        i.id,
        i.name,
        i.type,
        '${hardcore ? i.damage * 4 ~/ 5 : i.damage}',
        '${hardcore ? i.price * 3 ~/ 2 : i.price}',
        i.rarity,
      ],
  ];
  return rows.map((r) => r.map(_csvField).join(',')).map((l) => '$l\r\n').join();
}

const String enemiesTsv =
    'id\tname\thealth\tdamage\tspeed\txp\tfloor_min\tweakness\n'
    'slime\tNeon Slime\t30\t4\t1.2\t5\t1\tfire\n'
    'bat\tCave Bat\t18\t3\t3.5\t4\t1\tlight\n'
    'skeleton\tSkeleton\t45\t7\t2.0\t12\t2\tblunt\n'
    'skeleton-archer\tSkeleton Archer\t38\t9\t1.8\t15\t3\tblunt\n'
    'ghoul\tGhoul\t70\t10\t1.6\t22\t4\tfire\n'
    'mimic\tMimic\t120\t16\t1.0\t60\t5\t\n'
    'wraith\tWraith\t55\t12\t2.8\t30\t6\tlight\n'
    'neon-golem\tNeon Golem\t240\t22\t0.8\t110\t8\twater\n'
    'lich\tThe Laughing Lich\t900\t35\t1.4\t1000\t10\tlight\n';

Map<String, Object?> _hud({required bool neon}) => {
  'theme': neon ? 'neon' : 'classic',
  'version': 3,
  'font': {'family': 'PixelMono', 'size': 12, 'outline': true},
  'colors': neon
      ? {
          'text': '#FFE6EB',
          'accent': '#FF1744',
          'health': '#FF1744',
          'mana': '#FF6E86',
          'gold': '#FFC23D',
          'panel': '#0A0A0AD9',
        }
      : {
          'text': '#E0E0E0',
          'accent': '#4FC3F7',
          'health': '#E53935',
          'mana': '#1E88E5',
          'gold': '#FDD835',
          'panel': '#101010CC',
        },
  if (neon) 'glow': {'enabled': true, 'radius': 6, 'intensity': 0.8, 'pulseMs': 1200},
  'elements': [
    {'id': 'health_bar', 'anchor': 'top-left', 'x': 16, 'y': 16, 'width': 200, 'height': 14, 'visible': true},
    {'id': 'mana_bar', 'anchor': 'top-left', 'x': 16, 'y': 36, 'width': 160, 'height': 10, 'visible': true},
    {'id': 'gold_counter', 'anchor': 'top-left', 'x': 16, 'y': 54, 'icon': 'sprites/items/gem.png', 'visible': true},
    {
      'id': 'minimap',
      'anchor': 'top-right',
      'x': -16,
      'y': 16,
      'width': 160,
      'height': 160,
      'zoom': 1.5,
      'visible': true,
      'border': neon ? '#FF1744' : '#9E9E9E',
    },
    {'id': 'hotbar', 'anchor': 'bottom-center', 'x': 0, 'y': -24, 'slots': 6, 'slotSize': 40, 'visible': true},
    {'id': 'boss_bar', 'anchor': 'top-center', 'x': 0, 'y': 24, 'width': 480, 'height': 12, 'visible': false},
  ],
  'damageNumbers': {'enabled': true, 'critColor': neon ? '#FFFFFF' : '#FFEB3B', 'durationMs': 700},
  'crosshair': null,
};

String hudJson({bool neon = false}) => prettyJsonText(_hud(neon: neon));

Map<String, String> _strings({required bool patched}) => {
  'menu.title': 'NEON DUNGEON',
  'menu.play': 'Play',
  'menu.continue': 'Continue',
  'menu.options': 'Options',
  'menu.mods': 'Mods',
  'menu.quit': patched ? 'Quit' : 'Qiut',
  'hud.health': 'Health',
  'hud.mana': 'Mana',
  'hud.gold': 'Gold',
  'hud.floor': 'Floor {floor}',
  'item.pickup': 'Picked up {item} ×{count}',
  'item.recieve': patched ? 'You receive {item}.' : 'You recieve {item}.',
  'dialog.merchant.greeting': 'Welcome, traveller… care to trade?',
  'dialog.skull.laugh': 'HA HA HA — you will never escape!',
  'death.title': 'YOU DIED ☠',
  'death.hint': 'Press {key} to try again →',
  'achievement.floor10': '★ Ten floors deep ★',
  'credits.thanks': 'Thanks for playing ♥',
  'lang.others': 'Deutsch · Français · 日本語 · Русский · العربية',
  'save.corrupt': 'Save slot {slot} is damaged. Start over? «Yes» / «No»',
  if (patched) 'core_patch.banner': 'Core Patch 1.0.0 active – 3 fixes applied',
};

String enJson({bool patched = false}) => prettyJsonText({
  'language': 'en',
  'name': 'English',
  'gameVersion': sampleGameVersion,
  if (patched) 'patchedBy': 'core-patch 1.0.0',
  'strings': _strings(patched: patched),
});

String corePatchJson() => prettyJsonText({
  'id': 'core-patch',
  'version': '1.0.0',
  'description': 'Community fixes for Neon Dungeon 1.4.2 (fictional).',
  'fixes': [
    {'id': 'CP-001', 'area': 'localization', 'summary': 'Fix typos in menu.quit and item.recieve'},
    {'id': 'CP-002', 'area': 'ai', 'summary': 'Skeleton archers no longer shoot through walls'},
    {'id': 'CP-003', 'area': 'save', 'summary': 'Autosave interval raised from 60 to 120 seconds'},
  ],
  'flags': {'fixArcherLineOfSight': true, 'autosaveSeconds': 120, 'debugOverlay': false},
  'extensionPoints': ['balance', 'items'],
});

String saveSlot1Json() => prettyJsonText({
  'version': 2,
  'slot': 1,
  'savedAt': '2026-09-01T11:58:42Z',
  'player': {
    'name': 'J3NSONTOP',
    'class': 'necromancer',
    'level': 14,
    'xp': 18250,
    'health': 86,
    'gold': 1337,
    'position': {'x': 42.5, 'y': 17.25, 'floor': 6},
    'hardcore': false,
  },
  'inventory': [
    {'id': 'neon-blade', 'count': 1, 'equipped': true},
    {'id': 'tower-shield', 'count': 1, 'equipped': true},
    {'id': 'small-potion', 'count': 5},
    {'id': 'mana-potion', 'count': 3},
    {'id': 'dungeon-key', 'count': 2},
    {'id': 'red-gem', 'count': 1},
    {'id': 'laughing-skull', 'count': 1},
  ],
  'progress': {
    'floorsCleared': 5,
    'bossesDefeated': ['slime-king', 'bone-warden'],
    'difficulty': 'normal',
    'playTimeSeconds': 25310,
  },
});

String saveSchemaJson() => prettyJsonText({
  'title': 'Neon Dungeon save file',
  'description':
      'Save data written by Neon Dungeon 1.4.x (fictional). Uses the documented JSON Schema subset: '
      'type, title, description, properties, required, additionalProperties, items, minimum, maximum, '
      'minLength, maxLength, pattern, enum, default.',
  'type': 'object',
  'required': ['version', 'slot', 'player', 'inventory', 'progress'],
  'additionalProperties': false,
  'properties': {
    'version': {'type': 'integer', 'description': 'Save format version.', 'minimum': 1, 'maximum': 3},
    'slot': {'type': 'integer', 'minimum': 1, 'maximum': 3},
    'savedAt': {
      'type': 'string',
      'description': 'UTC timestamp, ISO 8601.',
      'pattern': r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$',
      'maxLength': 20,
    },
    'player': {
      'type': 'object',
      'title': 'Player',
      'required': ['name', 'class', 'level', 'health', 'gold'],
      'additionalProperties': false,
      'properties': {
        'name': {'type': 'string', 'minLength': 1, 'maxLength': 16, 'pattern': r'^[A-Za-z0-9_ -]+$'},
        'class': {
          'type': 'string',
          'enum': ['warrior', 'rogue', 'mage', 'necromancer'],
        },
        'level': {'type': 'integer', 'minimum': 1, 'maximum': 99},
        'xp': {'type': 'integer', 'minimum': 0, 'default': 0},
        'health': {'type': 'integer', 'minimum': 0, 'maximum': 999},
        'gold': {'type': 'integer', 'minimum': 0, 'maximum': 999999},
        'position': {
          'type': 'object',
          'required': ['x', 'y', 'floor'],
          'properties': {
            'x': {'type': 'number'},
            'y': {'type': 'number'},
            'floor': {'type': 'integer', 'minimum': 1, 'maximum': 20},
          },
        },
        'hardcore': {'type': 'boolean', 'default': false},
      },
    },
    'inventory': {
      'type': 'array',
      'description': 'Item stacks; ids refer to data/items.csv.',
      'items': {
        'type': 'object',
        'required': ['id', 'count'],
        'additionalProperties': false,
        'properties': {
          'id': {'type': 'string', 'pattern': r'^[a-z0-9-]+$', 'maxLength': 32},
          'count': {'type': 'integer', 'minimum': 1, 'maximum': 99},
          'equipped': {'type': 'boolean', 'default': false},
        },
      },
    },
    'progress': {
      'type': 'object',
      'properties': {
        'floorsCleared': {'type': 'integer', 'minimum': 0, 'maximum': 20},
        'bossesDefeated': {
          'type': 'array',
          'items': {
            'type': 'string',
            'enum': ['slime-king', 'bone-warden', 'neon-golem', 'laughing-lich'],
          },
        },
        'difficulty': {
          'type': 'string',
          'enum': ['easy', 'normal', 'hard', 'brutal'],
          'default': 'normal',
        },
        'playTimeSeconds': {'type': 'integer', 'minimum': 0},
      },
    },
  },
});

String cycleJson(String self, String other) => prettyJsonText({
  'id': self,
  'note': 'Demo package: $self depends on $other and $other depends on $self, so neither can be ordered first.',
  'value': 1,
});

const String todoMd = '''
# Neon Dungeon modding - to do

- [x] Back up the original `game/` folder (the Mods section does this for every apply)
- [x] Import the seven sample packages into the library
- [ ] Apply **Vanilla+ HUD** and compare `data/ui/hud.json` before/after
- [ ] Run **Hardcore run** and check that `core-patch` is applied first
- [ ] Try **Conflict demo** - who wins `config/balance.toml`?
- [ ] Look at **Broken dependencies**: `retro-core` does not exist, and `cycle-a` / `cycle-b` need each other
- [ ] Convert `config/controls.yaml` to JSON and find out what happened to `*look`
- [ ] Validate `saves/slot1.json` against `saves/save.schema.json`
- [ ] Set player gold to 1000000 and watch the validator complain (maximum is 999999)
- [ ] Slice `sprites/hero_walk.png` into 8 frames and preview the walk cycle
- [ ] Find the exact duplicates in `duplicates/` (one file only *looks* identical)
- [ ] Batch rename `rename-demo/` to `neon-shot-###.png`
- [ ] Find the first ERROR in `logs/game.log` and the root cause of the crash

## Notes

| What | Where |
| --- | --- |
| Game id / version | `game/game.json` -> neon-dungeon 1.4.2 |
| Mod library | workspace meta folder (managed by the Mods section) |
| Profiles | Vanilla+ HUD, Hardcore run, Conflict demo, Broken dependencies |

> Everything in this workspace is fictional and disposable. Reset it any time.
''';

const String unicodeNoteTxt =
    'Unicode file name demo: unicode-名前-ünïcødé.txt\n'
    '\n'
    '名前 (namae) means "name" in Japanese.\n'
    'Ünïcødé: diaereses and a slashed ø.\n'
    'Greek: Καλημέρα κόσμε\n'
    'Cyrillic: Привет, подземелье!\n'
    'Arabic (right-to-left): مرحبا بالعالم\n'
    'Hebrew (right-to-left): שלום עולם\n'
    'Emoji: 💀 🔥 🗡️ 🛡️ 💎 🔑\n'
    'Combining mark: é (e + U+0301) vs é (U+00E9) - look the same, different bytes\n'
    'Zero-width joiner: 👩‍💻 (three code points, one glyph)\n'
    'Box drawing: ┌──┐ │░▒▓│ └──┘\n';

const String screenShot1Txt =
    'Screen Shot 1\n'
    '\n'
    'Not really a screenshot: a text file with a messy name (spaces, mixed case)\n'
    'for the batch rename tool. Try renaming everything in rename-demo/ to\n'
    'neon-shot-###.<ext> with lower-case extensions.\n';

const String screenShot2Txt =
    'screen shot 2\n'
    '\n'
    'Same idea, different case and an upper-case .TXT extension.\n';
